### ISSUE TITLE
Unable to run the Main

### ISSUE THREAD

**Issue by Ramh5** [svanimpe/fx-game-loops#3]
Cloned the project into my eclipse workspace, I included jbox2d-library-2.1.2.3.jar though I was not sure what version and where to get it but I googled it and found http://www.java2s.com/Code/Jar/j/jbox2d.htm

Not sure if the jbox2d library is related to the problem but maybe.  Eclipse does not accept  the constructor for World(vec2) it wants to add a boolean after. But it still does not work with true or false.

private final World world = new World(new Vec2(0f, -10f));

**Comment by Ramh5** [comment]
I found a newer version of jbox2d 2.2.1.1 and it fixed the unrecognized World constructor but still get error messages

Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at svanimpe.fxgameloop.Main.start(Main.java:63)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	... 1 more
Exception running application svanimpe.fxgameloop.Main

**Comment by svanimpe** [comment]
Hi,

This project uses Maven, so you don't need to download any jars.

The included `pom.xml` was enough for me to run it from NetBeans, but you may need to extend it to run it elsewhere.

I've checked and it still runs fine in NetBeans 8.2 with the latest JDK 8. Other than that, I'm afraid I won't be of much help, as I no longer use Java.
